# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gagan Jain
full_name: Gagan Jain
email: gaganjain1582@gmail.com
# email2: kalpesh@cs.umass.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jain-gagan.github.io" # the base hostname & protocol for your site
github_username:  jain-gagan
# twitter_username: kalpeshk2011
linkedin_username: gaganjain15
# stackoverflow: 5080995/martianwars
include: ['_pages']
# footer-links-active:
  # stackoverflow: true

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
